// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbttqxsgumgifvduflbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idHRxeHNndW1naWZ2ZHVmbGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzOTA0NTMsImV4cCI6MjA1NTk2NjQ1M30.RSJ454nXchy1bcIpOjsKOpJddz3DFiiKNeQEMuX6pss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);